name: Loose Watercolor
favicon: null
layout_spectrum: 0.43835330312140286
typography_spectrum: 0.22609964641742408
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.10672392975538969
  lightness: 0.8782404980156571
  saturation: 0.2654683387372643
  rhythmicContrast: 0.57817826513201
purpose: []
